# Generated by Django 4.2.9 on 2024-01-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FullCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=256)),
                ('batch_date', models.DateField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=8, null=True)),
                ('sequential_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
